server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: order_service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/order/**

        - id: product_service
          uri: http://localhost:8082/
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*), /$\{path}
